ALTER TABLE `fee_xmfytj01`
MODIFY COLUMN `ZXGH` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '确认工号' AFTER `TJWH`,
MODIFY COLUMN `ZXRQ` datetime(0) NULL DEFAULT NULL COMMENT '确认日期' AFTER `ZXGH`,
MODIFY COLUMN `ZXPB` int(11) NULL DEFAULT NULL COMMENT '确认判别 | 0：未确认 1：已确认' AFTER `ZXRQ`,
MODIFY COLUMN `SXGH` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '生效/作废工号' AFTER `DSPB`,
MODIFY COLUMN `SXRQ` datetime(0) NULL DEFAULT NULL COMMENT '生效/作废日期' AFTER `SXGH`,
MODIFY COLUMN `SXPB` int(11) NULL DEFAULT NULL COMMENT '生效判别 | 0：未生效 1：已生效 2：作废' AFTER `SXRQ`,
COMMENT = '项目费用调价单主表';