ALTER TABLE `his`.`dic_gbsj02`
ADD COLUMN `OPERATOR_ID` int NULL COMMENT '操作人ID' AFTER `CAN_EXT`;
ALTER TABLE `his`.`dic_gbsj02`
ADD COLUMN `CREATE_ID` int NULL COMMENT '创建者ID' AFTER `OPERATOR_ID`;
ALTER TABLE `his`.`dic_gbsj01`
ADD COLUMN `OPERATOR_ID` int NULL COMMENT '操作人ID' AFTER `CAN_EXTEND`;