ALTER TABLE `his`.`phar_mzfymx`
MODIFY COLUMN `CFSB` bigint(0) NOT NULL COMMENT '处方识别 | 对应OP_CF01.CFSB代码' AFTER `FYRQ`,
MODIFY COLUMN `CFLX` int(0) NOT NULL COMMENT '处方类型 | 对应OP_CF01.CFLX代码' AFTER `CFSB`,
MODIFY COLUMN `FPHM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '发票号码 | 对应OP_CF01.FPHM代码' AFTER `CFLX`,
MODIFY COLUMN `KCSB` bigint(0) NOT NULL COMMENT '库存识别 | 对应DRUGS_KCMX.SBXH的代码' AFTER `JBYWBZ`;


ALTER TABLE `his`.`phar_kcdj`
MODIFY COLUMN `DJLB` int(0) NOT NULL COMMENT '冻结类别,1是门诊冻结,2是家床冻结,当类别是1的时候 CFSB存OP_CF01的主键,JLXH 存OP_CF02主键,  当类别是2时,CFSB存JC_BRYZ主键,JLXH 存JC_TJ02主键' AFTER `YFSB`;

ALTER TABLE `his`.`op_pdjh`
MODIFY COLUMN `JHHM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '叫号号码（OP_ghmx.pdxh）' AFTER `PMID`,
MODIFY COLUMN `GHSB` int(0) NULL DEFAULT NULL COMMENT '挂号识别（OP_ghmx.sbxh）' AFTER `BRID`,
MODIFY COLUMN `JHLY` int(0) NULL DEFAULT NULL COMMENT '叫号来源(1：OP_GHMX；2：OP_GHMX_ZZGH)' AFTER `TSRY`;

ALTER TABLE `his`.`op_mzxx`
MODIFY COLUMN `FPHM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '发票号码 | 连接OP_SFMX,OP_CF01,OP_YJ01' AFTER `JGID`,
MODIFY COLUMN `BRID` int(0) NULL DEFAULT NULL COMMENT '病人ID号 | 内部标示一个病人的编号在OP_BRDA库中每一个MZHM与一个ID号相关联，用于唯一标示一个病人' AFTER `SFRQ`,
MODIFY COLUMN `XJJE` decimal(12, 2) NOT NULL COMMENT '现金金额 | XJJE+ZPJE+QTJE+QTYS+HBWC= OP_SFMX中该发票的ZJJE之和但XJJE+ZPJE+QTJE不一定等于OP_SFMX中该发票的ZFJE之和' AFTER `DWXH`;


ALTER TABLE `his`.`drugs_rk02`
MODIFY COLUMN `TYPE` int(0) NULL DEFAULT NULL COMMENT '库存性质 NULL或0：正常\n其它对应SYS_DMZD（DMSB= 18 ）\n' AFTER `FPHM`,
MODIFY COLUMN `KCSB` int(0) NOT NULL COMMENT '与DRUGS_KCMX.SBXH对应' AFTER `BZLJ`;


ALTER TABLE `his`.`op_hzrb`
MODIFY COLUMN `XJJE` decimal(12, 2) NOT NULL COMMENT '现金金额 | 现金金额、支票金额、帐户自负(帐户金额)、其它应收、货币误差从OP_MZXX的XJJE,ZPJE,ZHJE,QTYS,HBWC中合计得到\n\n' AFTER `ZJJE`;

ALTER TABLE `his`.`opt_ssfl`
MODIFY COLUMN `SSNM` int(0) UNSIGNED NOT NULL COMMENT 'SYS_SSDM表主键' AFTER `ID`;

ALTER TABLE `his`.`op_zt01`
MODIFY COLUMN `ZTLX` int(0) UNSIGNED NULL DEFAULT NULL COMMENT '组套类型(关联SYS_ZTLX表主键ID)' AFTER `PLSX`;

ALTER TABLE `his`.`op_yjcf02`
MODIFY COLUMN `YLXH` int(0) NOT NULL COMMENT '医疗序号(关联SYS_YLSF费用序号FYXH字段)' AFTER `YJXH`,
MODIFY COLUMN `ZTYZSBXH` int(0) NULL DEFAULT NULL COMMENT '组套医嘱识别序号(OP_YJ02_ZT表SBXH)' AFTER `ZTBZ`;

ALTER TABLE `his`.`op_yj02_zt`
MODIFY COLUMN `YLXH` int(0) NOT NULL COMMENT '医疗序号(关联SYS_YLSF费用序号FYXH字段)' AFTER `YJXH`;

ALTER TABLE `his`.`op_sfmx`
MODIFY COLUMN `SFXM` int(0) NOT NULL COMMENT '收费项目 | 和SYS_SFXM的SFXM关联' AFTER `MZXH`,
MODIFY COLUMN `FPHM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '发票号码 | 通过此字段与OP_MZXX关联' AFTER `ZFJE`;

ALTER TABLE `his`.`op_rbmx`
MODIFY COLUMN `CZGH` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '操作工号 |  操作工号+结帐日期+收费项目通过CZGH+JZRQ和OP_HZRB关联\n收费项目和SYS_SFXM中SFXM关联\n' FIRST;

ALTER TABLE `his`.`op_mzxx`
MODIFY COLUMN `FPHM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '发票号码 | 连接OP_SFMX,MS_CF01,MS_YJ01' AFTER `JGID`,
MODIFY COLUMN `BRXB` int(0) NULL DEFAULT NULL COMMENT '病人性别 | 与SYS_DMZD（DMSB=15）对应' AFTER `BRXM`,
MODIFY COLUMN `BRXZ` int(0) NULL DEFAULT NULL COMMENT '病人性质 | 与SYS_BRXZ中BRXZ关联' AFTER `BRXB`,
MODIFY COLUMN `XJJE` decimal(12, 2) NOT NULL COMMENT '现金金额 | XJJE+ZPJE+QTJE+QTYS+HBWC= MS_SFMX中该发票的ZJJE之和但XJJE+ZPJE+QTJE不一定等于OP_SFMX中该发票的ZFJE之和' AFTER `DWXH`,
MODIFY COLUMN `ZHLB` int(0) NULL DEFAULT NULL COMMENT '帐户类别 | 与OP_ZHLB中CODE关联' AFTER `ZFJE`,
MODIFY COLUMN `GHGL` int(0) NULL DEFAULT NULL COMMENT '挂号关联 | 该收费单与哪次挂号相联系,GHGL字段与OP_GHMX中SBXH关联' AFTER `MZLB`;

ALTER TABLE `his`.`op_ghmx_ybbf`
MODIFY COLUMN `GHLB` int(0) NULL DEFAULT NULL COMMENT '挂号类别 | 与SYS_DMZD (DMLB = 25)关联' AFTER `GHSJ`,
MODIFY COLUMN `ZHLB` int(0) NULL DEFAULT NULL COMMENT '帐户类别 | 与ZHLB中CODE关联' AFTER `QTYS`,
MODIFY COLUMN `DDCS` int(0) NULL DEFAULT NULL COMMENT '等待次数  当前最大值-PDXH最大值' AFTER `DQXH`;

ALTER TABLE `his`.`op_ghmx`
MODIFY COLUMN `GHLB` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '挂号类别 | 与SYS_DMZD (DMLB = 25)关联' AFTER `GHSJ`,
MODIFY COLUMN `ZHLB` int(0) UNSIGNED NULL DEFAULT NULL COMMENT '帐户类别 | 与ZHLB中CODE关联' AFTER `QTYS`,
MODIFY COLUMN `DDCS` int(0) UNSIGNED NULL DEFAULT NULL COMMENT '等待次数  当前最大值' AFTER `DQXH`;

ALTER TABLE `his`.`op_ghks`
MODIFY COLUMN `GHLB` int(0) NULL DEFAULT NULL COMMENT '挂号类别 | 与SYS_DMZD (DMLB = 25)关联' AFTER `KSMC`;

ALTER TABLE `his`.`op_cf02`
MODIFY COLUMN `FYGB` int(0) NOT NULL COMMENT '费用归并 | 和SYS_SFXM的SFXM关联' AFTER `YCSL`;

ALTER TABLE `his`.`im_ryzd`
MODIFY COLUMN `ZDXH` int(0) NOT NULL COMMENT '诊断序号 | 对应SYS_JBZD的代码' AFTER `ZYH`,
MODIFY COLUMN `ZDLB` int(0) NOT NULL COMMENT '诊断类别 | 与SYS_DMZD（DMLB= 22）对应\n1：门诊诊断\n2：入院诊断\n3：出院主诊断\n4：出院次诊断\n5：院内感染\n' AFTER `ZDXH`,
MODIFY COLUMN `ZGQK` int(0) NULL DEFAULT NULL COMMENT '转归情况 | 与SYS_DMZD（DMLB= 23）对应\n1：治愈\n2：好转\n3：未愈\n4：死亡\n5：其他\n' AFTER `JGID`;

ALTER TABLE `his`.`im_rcjl`
MODIFY COLUMN `CYFS` int(0) NULL DEFAULT NULL COMMENT '出院方式 | 出院方式在CZLX=-1时使用，对应SYS_DMZD中的代码（DMLB = 23）' AFTER `BQPB`;

ALTER TABLE `his`.`im_cyjl`
MODIFY COLUMN `CYFS` int(0) NOT NULL COMMENT '出院方式 | 与SYS_DMZD（DMLB= 23）对应\n1：治愈\n2：好转\n3：未愈\n4：死亡\n5：其他\n' AFTER `CYSJ`;

ALTER TABLE `his`.`fee_ylsfxm`
MODIFY COLUMN `XMFL` int(0) UNSIGNED NULL DEFAULT NULL COMMENT '项目分类 | 维护为SYS_XMFLZD（项目分类字典）中的项目分类' AFTER `DZBH`;

ALTER TABLE `his`.`drugs_rk02`
MODIFY COLUMN `TYPE` int(0) NULL DEFAULT NULL COMMENT '库存性质 NULL或0：正常\n其它对应SYS_DMZD（DMSB= 18 ）\n' AFTER `FPHM`,
MODIFY COLUMN `KCSB` int(0) NOT NULL COMMENT '与DRUGS_KCMX.SBXH对应' AFTER `BZLJ`;

ALTER TABLE `his`.`dic_sfxmlb`
MODIFY COLUMN `LBDM` int(0) NULL DEFAULT NULL COMMENT '类别代码 | 对应SYS_SYFYGB的类别代码' AFTER `PLSX`;

ALTER TABLE `his`.`dic_sfxmlb`
MODIFY COLUMN `BXXM` int(0) NULL DEFAULT NULL COMMENT '保险项目 | 保险项目归并，与IM_DBXM中XMXH对应' AFTER `PYDM`;

ALTER TABLE `his`.`drugs_typk`
MODIFY COLUMN `YPSX` int(0) UNSIGNED NOT NULL COMMENT '药品属性 | 剂型代码\n对应DRUGS_YPSX.YPSX的代码' AFTER `BFGG`,
MODIFY COLUMN `TSYP` int(0) UNSIGNED NOT NULL COMMENT '特殊药品 | 对应SYS_DMZD（DMSB=16）对应\n1——麻醉、2——精神、3——贵重' AFTER `YPSX`,
MODIFY COLUMN `GYFF` int(0) UNSIGNED NULL DEFAULT NULL COMMENT '给药方法 | 对应IM_YPYF' AFTER `YPXQ`,
MODIFY COLUMN `ZBLB` int(0) UNSIGNED NOT NULL COMMENT '账簿类别,对应SYS_SFXM的 SFXM' AFTER `YQSYFS`;

ALTER TABLE `his`.`drugs_typk`
MODIFY COLUMN `FYFS` int(0) UNSIGNED NOT NULL COMMENT '发药方式 |药房发药根据发药方式统计各个病区的药品数量发药，对应IM_FYFS.FYFS的代码' AFTER `YLXZ`;

ALTER TABLE `his`.`im_fee_fymx`
MODIFY COLUMN `JFRQ` datetime(0) NOT NULL COMMENT '记费日期 | 实际记费日期\n写IM_FYMX时服务器时间\n' AFTER `ZXKS`,
MODIFY COLUMN `FYXM` int(0) NOT NULL COMMENT '费用项目 | 指定FYXH归并的项目(同SYS_SFMX表中SFXM对应)' AFTER `YPLX`,
MODIFY COLUMN `ZFBL` decimal(4, 3) NOT NULL COMMENT '自负比例 | 同SYS_ZFBL或 SYS_YPJY,SYS_FYJY表中自负比例对应' AFTER `JSCS`,
MODIFY COLUMN `YZXH` int(0) NULL DEFAULT NULL COMMENT '医嘱序号 | 同IM_BQYZ表中的医嘱序号对应' AFTER `ZFBL`;

ALTER TABLE `his`.`im_fee_fymx_js`
MODIFY COLUMN `FYXM` int(0) NOT NULL COMMENT '费用项目 | 指定FYXH归并的项目(同SYS_SFMX表中SFXM对应)' AFTER `YPLX`,
MODIFY COLUMN `ZFBL` decimal(4, 3) NOT NULL COMMENT '自负比例 | 同SYS_ZFBL或 SYS_YPJY,SYS_FYJY表中自负比例对应' AFTER `JSCS`;

ALTER TABLE `his`.`im_fee_fymx_yj`
MODIFY COLUMN `JFRQ` datetime(0) NOT NULL COMMENT '记费日期 | 实际记费日期\n写IM_FYMX_YJ时服务器时间\n' AFTER `ZXKS`,
MODIFY COLUMN `FYXM` int(0) NOT NULL COMMENT '费用项目 | 指定FYXH归并的项目(同SYS_SFMX表中SFXM对应)' AFTER `YPLX`,
MODIFY COLUMN `ZFBL` decimal(4, 3) NOT NULL COMMENT '自负比例 | 同SYS_ZFBL或 SYS_YPJY,SYS_FYJY表中自负比例对应' AFTER `JSCS`,
MODIFY COLUMN `YZXH` int(0) NULL DEFAULT NULL COMMENT '医嘱序号 | 同IM_BQYZ表中的医嘱序号对应' AFTER `ZFBL`;

ALTER TABLE `his`.`im_hcmx`
MODIFY COLUMN `HQCH` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '换前床号 | 与IM_CWSZ中的BRCH对应' AFTER `HCLX`,
MODIFY COLUMN `HHCH` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '换后床号 | 与IM_CWSZ中的BRCH对应' AFTER `HQCH`,
MODIFY COLUMN `HQKS` int(0) NULL DEFAULT NULL COMMENT '换前科室 | 与SYS_KSDM中科室对应' AFTER `HHCH`,
MODIFY COLUMN `HHKS` int(0) NULL DEFAULT NULL COMMENT '换后科室 | 与SYS_KSDM中科室对应' AFTER `HQKS`,
MODIFY COLUMN `JSCS` int(0) NULL DEFAULT NULL COMMENT '结算次数 | 同IM_BRRY,IM_ZYJS,IM_TBKK表中的JSCS 对应' AFTER `HHBQ`;

ALTER TABLE `his`.`im_hzry`
MODIFY COLUMN `BRXZ` int(0) NOT NULL COMMENT '病人性质 | 对应SYS_BRXZ中代码' AFTER `MZHM`,
MODIFY COLUMN `GFZH` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '公费证号 | 若IM_BRXZ中ZHPB为1则需填写该证号' AFTER `BRXZ`,
MODIFY COLUMN `DWBH` int(0) NULL DEFAULT NULL COMMENT '单位编号 | 对应与SYS_CYDW' AFTER `GJDM`,
MODIFY COLUMN `LXGX` int(0) NULL DEFAULT NULL COMMENT '联系人关系 | 与SYS_DMZD（DMLB=4）对应' AFTER `LXRM`,
MODIFY COLUMN `ZZTX` int(0) NULL DEFAULT NULL COMMENT '在职退休 | 与SYS_DMZD（DMLB=9）对应' AFTER `DBGX`,
MODIFY COLUMN `BRKS` int(0) NOT NULL COMMENT '病人科室 | 病人所在科室，对应SYS_KSDM的代码' AFTER `DBBZ`,
MODIFY COLUMN `BRBQ` int(0) NULL DEFAULT NULL COMMENT '病人病区 | 病人所在病区，对应SYS_KSDM的代码' AFTER `BRKS`,
MODIFY COLUMN `CYFS` int(0) NULL DEFAULT NULL COMMENT '出院方式 |与SYS_DMZD（DMLB= 23）对应\n1：治愈\n2：好转\n3：未愈\n5：死亡\n：其他\n' AFTER `CYPB`,
MODIFY COLUMN `RYQK` int(0) NULL DEFAULT NULL COMMENT '入院情况 | 与SYS_DMZD（DMLB=10）对应' AFTER `CZGH`,
MODIFY COLUMN `BRQK` int(0) NULL DEFAULT NULL COMMENT '病人情况 | 与SYS_DMZD（DMLB=10）对应' AFTER `RYQK`,
MODIFY COLUMN `YSDM` int(0) NULL DEFAULT NULL COMMENT '饮食代码 | 与SYS_DMZD（DMLB=20）对应' AFTER `HLJB`,
MODIFY COLUMN `BRXX` int(0) NULL DEFAULT NULL COMMENT '病人血型 | 与SYS_DMZD（DMLB=21）对应' AFTER `YSDM`,
MODIFY COLUMN `MZYS` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '门诊医生 | 对应SYS_YGDM中的YGDM的代码' AFTER `JCKS`,
MODIFY COLUMN `ZYYS` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '住院医生 | 对应SYS_YGDM中的YGDM的代码' AFTER `MZYS`,
MODIFY COLUMN `ZSYS` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '主任医生 | 对应SYS_YGDM中的YGDM的代码' AFTER `ZYYS`,
MODIFY COLUMN `ZZYS` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '主治医生 | 对应SYS_YGDM中的YGDM的代码' AFTER `ZSYS`,
MODIFY COLUMN `SZYS` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '主治医生 | 指接收病人的医生，对应SYS_YGDM中的YGDM的代码' AFTER `JZKH`,
MODIFY COLUMN `ZLXZ` int(0) NULL DEFAULT NULL COMMENT '诊疗小组 | 指负责病人治疗的医疗小组，对应IM_ZLXZ.XZXH的代码' AFTER `SZYS`,
MODIFY COLUMN `DJID` int(0) NULL DEFAULT NULL COMMENT '冻结ID号 | 对应IM_ZHDJ.DJID的代码' AFTER `DJBZ`;

ALTER TABLE `his`.`im_jzxx`
MODIFY COLUMN `TYJJ` decimal(12, 2) NOT NULL COMMENT '退预交金 | 同IM_JZXX.YSJE' AFTER `ZPZS`,
MODIFY COLUMN `SRJE` decimal(6, 2) NOT NULL COMMENT '舍入金额 | 同IM_ZYJS.SRJE' AFTER `QTZS`;

ALTER TABLE `his`.`im_tbkk`
MODIFY COLUMN `JKFS` int(0) NULL DEFAULT NULL COMMENT '缴款方式 | 1:现金,2:支票(与IM_JKFS表中JKFS字段对应' AFTER `JKJE`,
MODIFY COLUMN `JSCS` int(0) NULL DEFAULT NULL COMMENT '结算次数 | 同IM_BRRY,IM_ZYJS,IM_FYMX表中JSCS\nJSCS=0 则病人尚未办理结算.' AFTER `FPHM`;

ALTER TABLE `his`.`nis_tj02`
MODIFY COLUMN `FYMXJLXH` int(0) NULL DEFAULT NULL COMMENT 'IM_FYMX表的主键JLXH，只有手术记的药品才会存' AFTER `QRGH`;

ALTER TABLE `his`.`nis_yzdy`
MODIFY COLUMN `YZBXH` int(0) NULL DEFAULT NULL COMMENT '医嘱本序号,对应IM_BQYZ的JLXH' AFTER `DYXH`;

ALTER TABLE `his`.`phar_fyjl`
MODIFY COLUMN `YFSB` int(0) NULL DEFAULT NULL COMMENT '药房识别 | 对应PHAR_YFLB的代码' AFTER `FYLX`,
MODIFY COLUMN `FYFS` int(0) NOT NULL COMMENT '发药方式 | 对应IM_FYFS中的代码' AFTER `YFSB`;

ALTER TABLE `his`.`phar_zyfymx`
MODIFY COLUMN `JFID` int(0) NOT NULL COMMENT '记费ID | 与IM_FYMX中的 JLXH 对应' AFTER `TYGL`,
MODIFY COLUMN `TJXH` int(0) NULL DEFAULT NULL COMMENT '提交序号 | 对应NIS_TJ02的主键序号值' AFTER `KCSB`,
MODIFY COLUMN `TYXH` int(0) NULL DEFAULT NULL COMMENT '退药序号 | 对应NIS_TYMX表的主键值' AFTER `TJXH`;