ALTER TABLE `dic_yljg`
ADD COLUMN `PAGELOGO1` varchar(255) NULL COMMENT '首页小图片1路径',
ADD COLUMN `PAGELOGO2` varchar(255) NULL COMMENT '首页小图片2路径',
ADD COLUMN `PAGELOGO3` varchar(255) NULL COMMENT '首页小图片3路径',
ADD COLUMN `PAGELOGO4` varchar(255) NULL COMMENT '首页小图片4路径',
ADD COLUMN `PAGELOGO5` varchar(255) NULL COMMENT '首页小图片5路径';
